services:
  api:
    container_name: slotmachine_api
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - postgres
  postgres:
    container_name: slotmachine_postgres
    image: postgres:13-alpine
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_HOST_PORT}:${DB_PORT}
    volumes:
      - api_db_data:/var/lib/postgresql/data
networks:
  backend:
volumes:
  api_db_data:
