export const USER_EXIST = 'USER_EXIST';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const USER_ALREADY_VALIDATED = 'USER_ALREADY_VALIDATED';
export const USER_NOT_ACTIVED = 'USER_NOT_ACTIVED';
export const USER_PASS_EMPTY = 'USER_PASS_EMPTY';
export const USER_INVALID_CODE = 'USER_INVALID_CODE';
export const USER_PASS_ALREADY_DEFINED = 'USER_PASS_ALREADY_DEFINED';
export const USER_ROLE_NOT_FOUND = 'USER_ROLE_NOT_FOUND';
export const USER_IS_BLOCKED = 'USER_IS_BLOCKED';
export const DUPLICATE_EMAIL = 'DUPLICATE_EMAIL';

export const INVALID_PASSWORD = 'INVALID_PASSWORD';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';

export const UNAUTHORIZED_USER = 'UNAUTHORIZED_USER';
