name: CI Pipeline

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.17
      - run: yarn install
      - run: yarn build
      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: dist/
          key: ${{ runner.os }}-build-${{ github.sha }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.17
      - run: yarn install
      - run: yarn test
